### ISSUE TITLE
Shield Counters from Arena?

### ISSUE THREAD

**Issue by JustAMalcontent** [andrewgioia/mana#90] opened 2022-06-11 00:49 UTC
Is there any possibility of including an icon for Shield Counters?

**Comment by ThePieBandit** [comment] 2022-11-20 01:37
+1

**Comment by andrewgioia** [comment] 2023-02-24 14:07
Yes absolutely @JustAMalcontent I need to get a full list of all of the new ability icons and counters that have been added to Arena and MODO since the last update 😬

**Comment by ThePieBandit** [comment] 2023-02-25 18:35
Duplicate of #94 at this point since all the tracking is done there?

**Closed** 2023-03-03 19:07 UTC
Labels: duplicate, new-icon
